# Generated by Django 5.0.6 on 2024-05-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.IntegerField(),
        ),
    ]
